// Copyright (c) 2021 Razeware LLC

/// Flutter icons Pets
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.

// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';
//Icons made by "https://www.flaticon.com/authors/freepik"

class Pets {
  Pets._();

  static const _kFontFam = 'Pets';

  static const IconData cat = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData dog_seating = IconData(0xe801, fontFamily: _kFontFam);
}
